### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by nadavtal** [markerikson/cesium-react-webpack-demo#6]
getting this error out of the box. any idea why?

**Comment by markerikson** [comment]
Nope, sorry.  I'd suggest updating the dependencies and trying again.

**Comment by markerikson** [comment]
As an additional note: I would no longer recommend trying to set up Cesium by hand as seen in this repo.  Instead, I recommend:

- Create a Create-React-App project (https://facebook.github.io/create-react-app/)
- Add the `craco` CRA override tool: https://github.com/sharegate/craco
- Add the `craco-cesium` plugin: https://github.com/darwin-education/craco-cesium
- Use the Resium library, which provides React components that wrap Cesium: https://resium.darwineducation.com/

**Comment by nadavtal** [comment]
Thankyou very much. Thats what im doing. Having some trouble with  it though

בתאריך יום ג׳, 3 בדצמ׳ 2019, 23:13, מאת Mark Erikson ‏<
notifications@github.com>:
